# Generated by Django 4.2.17 on 2025-01-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users1', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_logos/'),
        ),
    ]
